version: "3"


services:
  postgresql:
    image: postgres:12-alpine
    hostname: $${POSTGRES_HOST}
    container_name: matemeet-postgresql
    env_file:
      - backend/services/postgresql/.env
    ports:
      - 5432:5432
    volumes:
      - pg-data-matemeet:/var/lib/postgresql/data


  backend:
    image: matemeet-backend
    container_name: django-backend
    user: appuser
    build: backend/services/backend
    env_file:
      - backend/services/backend/.env
      - backend/services/postgresql/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend/services/backend/service/api:/home/appuser/project/api/
      - ./backend/services/backend/service/apps:/home/appuser/project/apps/
      - ./backend/services/backend/service/libs:/home/appuser/project/libs/
      - ./backend/services/backend/service/static:/home/appuser/project/static/
      - ./backend/services/backend/service/locales:/home/appuser/project/locales/
      - ./backend/services/backend/service/settings:/home/appuser/project/settings/
    depends_on:
      - postgresql
    command: /bin/bash -c "
      ./wait-for.sh $${POSTGRES_HOST}:$${POSTGRES_PORT} &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"


  broker-redis:
    container_name: broker-redis
    image: redis:5-alpine
    expose:
      - 6379
  beat:
    container_name: beat
    entrypoint: [ 'celery' ]
    command: [ 'beat', '-A', 'service.apps.celery.celery' ]
    build:
      context: ./backend/services/backend
    volumes:
      - ./backend/services/backend/service:/home/appuser/project/
    depends_on:
      - postgresql
      - broker-redis
  worker:
    container_name: worker
    entrypoint: ['celery']
    command: ['worker', '-A', 'service.apps.celery.celery']
    build:
      context: ./backend/services/backend
    volumes:
      - ./backend/services/backend/service:/home/appuser/project/
    depends_on:
      - postgresql
      - broker-redis
volumes:
  pg-data-matemeet:
